version: '3'
services:
  spark-master:
    build: 
      context: .
      dockerfile: Dockerfile
    image: spark
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    environment:
      SPARK_MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes: 
      - type: bind 
        source: ./
        target: /mnt/keywords
      - type: bind 
        source: .
        target: /mnt/input
      - ./conf/master:/conf
      - ./data:/tmp/data

  spark-slave-1:
    container_name: spark-slave-1
    image: spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-slave-1
    depends_on: [spark-master]
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    ports:
      - 8081:8081
    volumes:
      - type: bind 
        source: ./
        target: /mnt/keywords
      - type: bind 
        source: .
        target: /mnt/input
      - ./conf/worker:/conf
      - ./data:/tmp/data
